# Generated by Django 2.2.1 on 2020-04-22 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chaice',
            new_name='Choice',
        ),
    ]
